version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8010:8010"
    environment:
      PDF2MD_PROJECT_ROOT: /src
    volumes:
      - ./app:/src/app
      - ./data:/src/data:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./pdf-upload-app:/src/pdf-upload-app
      - ./package.json:/src/package.json