export type Availability={status:string;available:boolean;reason?:string|null;stage?:string|null};
export type ApiElement={element:Record<string,any>;canonical_rendering?:string|null};
export type CatalogDoc={id:string;split:string;local_path?:string;metadata?:Record<string,any>};
export type CatalogEntry={document:CatalogDoc;original_source:Availability;candidate:Availability;reference:Availability;gold:null|Availability};
export function backendSplit(label:string){return label==='test'?'holdout':label}
export async function apiFetch<T>(path:string, signal?:AbortSignal):Promise<T>{const response=await fetch(path,{signal});if(!response.ok) throw new Error(`${response.status}: ${await response.text()}`);return response.json() as Promise<T>}
export const api={documents:(split:string,signal?:AbortSignal)=>apiFetch<{documents:CatalogEntry[]}>(`/comparison/documents?split=${encodeURIComponent(backendSplit(split))}`,signal),document:(id:string,signal?:AbortSignal)=>apiFetch<any>(`/comparison/documents/${encodeURIComponent(id)}`,signal),elements:(id:string,source:'candidate'|'reference',signal?:AbortSignal)=>apiFetch<{elements:ApiElement[];source:string;stage:string}>(`/comparison/documents/${encodeURIComponent(id)}/elements/${source}`,signal),evaluation:(id:string,signal?:AbortSignal)=>apiFetch<any>(`/comparison/documents/${encodeURIComponent(id)}/evaluation`,signal)};
export function field(element:ApiElement|undefined,key:string, fallback=''){return element?.element?.[key] ?? fallback}
export function bboxOf(element:ApiElement|undefined):[number,number,number,number]|null{const fragment=element?.element?.fragments?.[0];const b=fragment?.bbox??element?.element?.bbox??element?.element?.geometry?.bbox;if(Array.isArray(b)&&b.length===4)return b.map(Number) as [number,number,number,number];if(b&&typeof b==='object'){const values=['x0','y0','x1','y1'].map(key=>Number((b as Record<string,unknown>)[key]));if(values.every(Number.isFinite))return values as [number,number,number,number]}return null}
export function pageOf(element:ApiElement|undefined){return Number(element?.element?.fragments?.[0]?.page_number??element?.element?.page_number??element?.element?.page??element?.element?.source?.page??1)}
export function bboxToCss(b:[number,number,number,number], pageWidth:number, pageHeight:number){if(pageWidth<=0||pageHeight<=0||b[2]<b[0]||b[3]<b[1]) return null;return {left:b[0]/pageWidth*100,bottom:b[1]/pageHeight*100,width:(b[2]-b[0])/pageWidth*100,height:(b[3]-b[1])/pageHeight*100}}
export function geometryOf(element:ApiElement|undefined){const f=element?.element?.fragments?.[0];return {width:Number(f?.page_width||0),height:Number(f?.page_height||0),rotation:Number(f?.rotation||0)}}
